version: '3'
services:
  authentication:
    build: .
    ports:
     - "8081:8081"
    links:
      - docker-mysql
    environment:
      DATABASE_HOST: 'docker-mysql'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
      DATABASE_NAME: 'user_credentials'
      DATABASE_PORT: 3306
  docker-mysql:
    ports:
      - "3306:3306"
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'user_credentials'
      MYSQL_ROOT_HOST: '%'
      
